tick = 500 # Check every 500ms

# Some action
[[action]]
name = "some action" # Name used in output
exec = [] # Command to execute when criteria is met
undo = [] # Command to execute when criteria is no longer met

# Must match this criteria
[[action.criteria]]
user = [] # ["$USER"] - Owned by same user running paction
name = [] # ["mygame"] - This game of mine
cmd = [] # ["--fullscreen", "--borderless"] - Command contains one of these

# Also must match this criteria
[[action.criteria]]
user = [] # ["someuser", 1001, "$USER"] - Owned by either
name = [] # ["someprog", "orthisprog"] - One of these programs
cmd = []

# Some other action
[[action]]
name = "some other action" # Name used in output
exec = [] # Command to execute when criteria is met
undo = [] # Command to execute when criteria is no longer met

# Must match this criteria
[[action.criteria]]
user = [] # ["someuser"] - Owned by "someuser"
name = []
cmd = [] # ["--fullscreen", "--borderless"] - Command contains one of these
